version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - course_network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: course_assistant
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - course_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - course_network
    volumes:
      - ollama_data:/root/.ollama

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=course_assistant
      - POSTGRES_USER=course_user
      - POSTGRES_PASSWORD=course_password
      - POSTGRES_PORT=5432
      - OPENAI_BASE_URL=http://ollama:11434/v1
      - OPENAI_API_KEY=ollama
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - INDEX_NAME=course-questions
      - LLM_MODEL=phi3
    depends_on:
      - elasticsearch
      - postgres
      - ollama
    networks:
      - course_network
    volumes:
      - .:/app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - course_network
    depends_on:
      - postgres

volumes:
  elasticsearch_data:
    driver: local
  postgres_data:
    driver: local
  ollama_data:
    driver: local
  grafana_data:
    driver: local

networks:
  course_network:
    driver: bridge