version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - course_network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: course_assistant
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - course_network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9201
      - INDEX_NAME=course-questions
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=course_assistant
      - POSTGRES_USER=course_user
      - POSTGRES_PASSWORD=course_password
      - POSTGRES_PORT=5432
      - OPENAI_BASE_URL=http://ollama:11434/v1/
      - OPENAI_API_KEY=ollama
      - LLM_MODEL=phi3
    depends_on:
      - elasticsearch
      - postgres
      - ollama
    networks:
      - course_network
    volumes:
      - .:/app

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - course_network
    volumes:
      - ollama_data:/root/.ollama

volumes:
  elasticsearch_data:
    driver: local
  postgres_data:
    driver: local
  ollama_data:
    driver: local

networks:
  course_network:
    driver: bridge
